import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Hero from "./_components/hero";
import BorderAnimation from "./_components/border-animation";
import Navbar from "./_components/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className=" h-screen w-screen flex flex-col overflow-hidden">
            <Navbar />
            <div className="h-[90%] w-screen flex ">
              <BorderAnimation />
              <div className="h-full w-[86%] border-x">
                {children}
              </div>
              <BorderAnimation />
            </div>

          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
